In [36]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans,MiniBatchKMeans
from sklearn.datasets import make_blobs,load_digits
from sklearn.linear_model import LogisticRegression

In [4]:
make_blobs

<function sklearn.datasets._samples_generator.make_blobs(n_samples=100, n_features=2, *, centers=None, cluster_std=1.0, center_box=(-10.0, 10.0), shuffle=True, random_state=None, return_centers=False)>

In [8]:
X, y = make_blobs(n_samples=100, n_features=5, centers=3 , random_state=42)


In [13]:
X[1]

array([-5.97037142, -9.04078528,  7.38441952,  2.66946293,  4.28754638])

In [23]:
 np.unique(y)

array([0, 1, 2])

In [24]:
k=3

In [25]:
kmeans=KMeans(n_clusters=k,random_state=45)

In [26]:
y_pred=kmeans.fit_predict(X)

C:\Users\USMAN KHALID\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
C:\Users\USMAN KHALID\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1440: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


In [27]:
y_pred[:5]

array([0, 1, 0, 0, 0])

In [20]:
y[:5]

array([0, 1, 0, 0, 0])

# CHOOSING THE BEST K

# elbow method

# silhouette score

In [28]:
from sklearn.metrics import silhouette_score
silhouette_score(X,kmeans.labels_)

0.777435321275294

In [29]:
#  image segmentation with kmeans
import PIL

In [31]:
X_digit,X_digit=load_digits(return_X_y=True)

In [33]:
X_digit

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [32]:
y_digit

array([0, 1, 2, ..., 8, 9, 8])

In [43]:
X_Train, y_train=X_digit[:1400],y_digit[:1400]
X_Test, y_test=X_digit[1400:],y_digit[1400:]

In [44]:
model1=LogisticRegression(max_iter=10_000)

In [49]:
model1.fit(X_Train[:200],y_train[:200])

LogisticRegression(max_iter=10000)

In [50]:
model1.score(X_Test,y_test)

0.8236775818639799

In [51]:
modelk=KMeans(n_clusters=200,random_state=45)

In [53]:
X_digit_dict=modelk.fit_transform(X_Train)

C:\Users\USMAN KHALID\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
C:\Users\USMAN KHALID\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1440: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=6.
  warnings.warn(


In [55]:
representative_digit_idx=np.argmin(X_digit_dict,axis=0)

In [56]:
representative_digit=X_Train[representative_digit_idx]

In [57]:
representative_digit

array([[ 0.,  0.,  6., ...,  3.,  0.,  0.],
       [ 0.,  0.,  7., ..., 10.,  0.,  0.],
       [ 0.,  0.,  3., ...,  8.,  0.,  0.],
       ...,
       [ 0.,  0., 13., ...,  0.,  0.,  0.],
       [ 0.,  0.,  8., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [59]:
model1.fit(representative_digit,y_train[:200])

LogisticRegression(max_iter=10000)

In [60]:
model1.score(X_Test,y_test)

0.14105793450881612