In [1]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans,MiniBatchKMeans,DBSCAN
from sklearn.datasets import make_blobs,load_digits,make_moons
from sklearn.linear_model import LogisticRegression

In [2]:
X,y=make_moons(n_samples=1000,noise=0.05)
dbscan=DBSCAN(eps=0.05,min_samples=5)
dbscan.fit(X)

DBSCAN(eps=0.05)

In [3]:
dbscan.labels_

array([ 0,  1, -1,  1,  2,  0,  3,  0,  4,  1, -1,  5,  0,  0,  4,  0,  1,
        4,  5, -1,  4,  5,  6, -1,  7,  6,  7,  1,  6, -1,  0,  6,  0,  0,
        6,  5,  7,  3,  1,  1,  3,  1,  0,  1,  0,  2,  1, -1, -1,  6,  1,
        5, -1,  0,  0,  1, -1,  1,  1, -1,  4,  1,  7,  3,  0,  0,  0,  1,
        4,  0,  8,  0, -1,  4,  5, -1,  4,  0,  3,  1,  1,  6, -1,  1,  4,
        1,  0,  4,  2,  0,  0,  3, -1,  0,  0,  0,  5,  1,  5,  1,  5,  3,
        0,  0,  0,  0,  0,  5,  0,  1,  7,  4,  1,  1,  1,  1,  0,  1,  0,
        4,  1,  1,  1,  4,  6,  0,  0,  0,  6,  4,  1,  4,  1,  4,  3,  3,
        3,  0,  5,  4,  0,  0,  5,  1,  6,  1,  1,  1,  9,  3,  0,  0,  3,
        1,  1, -1,  0,  1,  5,  8,  4,  0, -1,  6,  0,  0,  0,  7,  6,  6,
        1,  1,  3,  1,  1,  8,  0,  3,  7,  3,  7,  3,  5,  6, -1,  0,  0,
        0,  0,  6,  1,  4,  3,  3, -1, -1,  2,  0,  0,  7,  1,  1, -1,  6,
        1,  1,  0, -1,  4,  0, -1,  1,  1,  1,  0,  1,  0,  0,  6,  3,  1,
        1,  4, -1,  5,  6

In [4]:
dbscan.core_sample_indices_

array([  0,   1,   3,   4,   6,   7,   8,   9,  11,  12,  13,  14,  15,
        17,  18,  20,  21,  22,  24,  25,  26,  27,  28,  30,  32,  33,
        34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  45,  46,  49,
        50,  54,  55,  57,  58,  61,  62,  63,  64,  65,  66,  67,  68,
        69,  70,  71,  73,  74,  76,  77,  78,  79,  80,  81,  83,  84,
        85,  86,  87,  88,  89,  90,  91,  93,  94,  95,  96,  97,  99,
       100, 101, 102, 103, 104, 105, 106, 108, 109, 110, 111, 112, 114,
       115, 116, 117, 118, 119, 121, 123, 124, 125, 126, 128, 129, 130,
       131, 132, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149, 150, 152, 153, 154, 157, 158, 159, 160,
       161, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
       176, 177, 178, 179, 180, 181, 182, 183, 185, 186, 187, 188, 189,
       190, 191, 192, 193, 196, 197, 198, 199, 200, 201, 203, 204, 205,
       206, 209, 211, 212, 213, 214, 216, 218, 219, 220, 221, 22

In [5]:
dbscan.components_

array([[ 0.22685141, -0.1218268 ],
       [-0.92005848,  0.46466411],
       [-0.32955667,  0.9299162 ],
       ...,
       [-0.23663375,  0.97181823],
       [-0.56339964,  0.82943208],
       [ 0.95320165, -0.5188387 ]])

In [8]:
from sklearn.neighbors import KNeighborsClassifier 
kn_clr=KNeighborsClassifier(n_neighbors=50)
kn_clr.fit(dbscan.components_, dbscan.labels_[dbscan.core_sample_indices_])

KNeighborsClassifier(n_neighbors=50)